version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: your_database_name
      POSTGRES_USER: your_database_user
      POSTGRES_PASSWORD: your_database_password
    ports:
      - "5432:5432"
    networks:
      - my-network

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
